# Generated by Django 4.2.3 on 2023-07-05 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uacs_app', '0003_squad_tribe_remove_staff_designation_staff_role_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='designation',
        ),
        migrations.AddField(
            model_name='admin',
            name='role',
            field=models.CharField(choices=[('Intern', 'Intern'), ('Associate', 'Associate'), ('VP', 'VP'), ('Analyst', 'Analyst'), ('Manager', 'Manager'), ('Head', 'Head'), ('Managing Director', 'Managing Director')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='squad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uacs_app.squad'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='tribe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uacs_app.tribe'),
        ),
    ]
