# Generated by Django 4.2.3 on 2023-07-05 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uacs_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviderActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('actor', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('Updated', 'Updated'), ('Created', 'Created')], max_length=20)),
                ('service_provider', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('actor', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('Updated', 'Updated'), ('Created', 'Created'), ('Restored', 'Restored')], max_length=20)),
                ('permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_activity', to='uacs_app.staffpermission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
