# Generated by Django 4.2.3 on 2023-07-05 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uacs_app', '0002_serviceprovideractivitylog_staffactivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='staff',
            name='designation',
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Intern', 'Intern'), ('Associate', 'Associate'), ('VP', 'VP'), ('Analyst', 'Analyst'), ('Manager', 'Manager'), ('Head', 'Head'), ('Managing Director', 'Managing Director')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffactivitylog',
            name='action',
            field=models.CharField(choices=[('Updated', 'Updated'), ('Restored', 'Restored'), ('Revoked', 'Revoked')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='squad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uacs_app.squad'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='tribe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uacs_app.tribe'),
        ),
    ]
