# Generated by Django 4.2.3 on 2023-07-05 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uacs_app', '0003_squad_tribe_remove_staff_designation_staff_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('Updated', 'Updated'), ('Restored', 'Restored'), ('Revoked', 'Revoked'), ('Created', 'Created')], max_length=15)),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default=dict)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-action_time'],
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('role', models.CharField(choices=[('Intern', 'Intern'), ('Associate', 'Associate'), ('VP', 'VP'), ('Analyst', 'Analyst'), ('Manager', 'Manager'), ('Head', 'Head'), ('Managing Director', 'Managing Director')], max_length=100, null=True)),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uacs_app.squad')),
                ('tribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uacs_app.tribe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ServiceProviderActivityLog',
        ),
        migrations.DeleteModel(
            name='StaffActivityLog',
        ),
    ]
