# Generated by Django 4.2.3 on 2023-07-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uacs_app', '0005_designation_admin_designation_staff_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], default='Success', max_length=7),
        ),
    ]
