# Generated by Django 4.2.3 on 2023-07-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uacs_app', '0007_alter_serviceprovider_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='squad',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tribe',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
