# Generated by Django 4.2.3 on 2023-07-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uacs_app', '0008_alter_designation_name_alter_squad_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('Updated', 'Updated'), ('Restored', 'Restored'), ('Revoked', 'Revoked'), ('Created', 'Created'), ('Login', 'Login'), ('Logout', 'Logout')], max_length=15),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='sp_picture/'),
        ),
    ]
