# Generated by Django 4.2.3 on 2023-07-10 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uacs_app', '0009_admin_profile_picture_staff_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='data',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(blank=True, choices=[('Updated', 'Updated'), ('Restored', 'Restored'), ('Revoked', 'Revoked'), ('Created', 'Created'), ('Login', 'Login'), ('Logout', 'Logout')], null=True),
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(blank=True, choices=[('Updated', 'Updated'), ('Restored', 'Restored'), ('Revoked', 'Revoked'), ('Created', 'Created'), ('Login', 'Login'), ('Logout', 'Logout')], null=True)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], default='Success', max_length=7)),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-action_time'],
            },
        ),
    ]
