# Generated by Django 4.2.3 on 2023-07-12 14:40

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('uacs_app', '0010_remove_activitylog_data_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='staff',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='securitylog',
            name='ip_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='profile_picture',
            field=models.ImageField(default='static/images/pi.png', upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='profile_picture',
            field=models.ImageField(default='static/images/pi.png', upload_to='profile_pictures/'),
        ),
    ]
