# Generated by Django 4.2.3 on 2023-07-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uacs_app', '0011_alter_staff_managers_securitylog_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
