# Generated by Django 4.2.3 on 2023-07-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uacs_app', '0014_alter_staff_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceprovider',
            options={'ordering': ['-created_date']},
        ),
    ]
