UPDATED = "Updated"
REVOKED = "Revoked"
RESET = "Restored"
CREATED = "Created"
LOGIN = "Login"
ANALYST = "Analyst"
HEAD = "Head"
ASSOCIATE = "Associate"
INTERN = "Intern"
VP = "VP"
MANAGER = "Manager"
MANAGING_DIRECTOR = "Managing Director"

LOGIN, LOGOUT, LOGIN_FAILED = "Login", "Logout", "Login Failed"
SUCCESS, FAILED = "Success", "Failed"
ACTION_STATUS = [(SUCCESS, SUCCESS), (FAILED, FAILED)]